name: Code Quality Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies run Lint and Test
        run: |
          npm install
          npm run lint
          npm test

      - name: Build
        run: |
          npm run build
          npm run docker:build

